# Project: CTDL
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main_CTDL.o Dic.o Chuoi.o File.o Dictionary.o
LINKOBJ  = main_CTDL.o Dic.o Chuoi.o File.o Dictionary.o
LIBS     = -L"D:/c++/C++_Graphic/Dev_C++/Dev-Cpp 5.11 TDM-GCC x64 4.9.2 Portable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -lbgi -lgdi32 -luser32 -m32 -g3
INCS     = -I"D:/c++/C++_Graphic/Dev_C++/Dev-Cpp 5.11 TDM-GCC x64 4.9.2 Portable/Dev-Cpp/MinGW64/include" -I"D:/c++/C++_Graphic/Dev_C++/Dev-Cpp 5.11 TDM-GCC x64 4.9.2 Portable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/c++/C++_Graphic/Dev_C++/Dev-Cpp 5.11 TDM-GCC x64 4.9.2 Portable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/c++/C++_Graphic/Dev_C++/Dev-Cpp 5.11 TDM-GCC x64 4.9.2 Portable/Dev-Cpp/MinGW64/include" -I"D:/c++/C++_Graphic/Dev_C++/Dev-Cpp 5.11 TDM-GCC x64 4.9.2 Portable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/c++/C++_Graphic/Dev_C++/Dev-Cpp 5.11 TDM-GCC x64 4.9.2 Portable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/c++/C++_Graphic/Dev_C++/Dev-Cpp 5.11 TDM-GCC x64 4.9.2 Portable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = CTDL.exe
CXXFLAGS = $(CXXINCS) -m32 -g3
CFLAGS   = $(INCS) -m32 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main_CTDL.o: main_CTDL.cpp
	$(CPP) -c main_CTDL.cpp -o main_CTDL.o $(CXXFLAGS)

Dic.o: Dic.cpp
	$(CPP) -c Dic.cpp -o Dic.o $(CXXFLAGS)

Chuoi.o: Chuoi.cpp
	$(CPP) -c Chuoi.cpp -o Chuoi.o $(CXXFLAGS)

File.o: File.cpp
	$(CPP) -c File.cpp -o File.o $(CXXFLAGS)

Dictionary.o: Dictionary.cpp
	$(CPP) -c Dictionary.cpp -o Dictionary.o $(CXXFLAGS)
